AENA_INFOVUELOS_URL = "http://www.aena.es/csee/Satellite/infovuelos/es/"
AENA_BASE_URL = "http://www.aena.es"
LOCAL_INFOVUELOS_URL = "resources/infovuelos.html"
LOCAL_SAMPLE_DEPARTURES = "resources/lcg-departures.html"
DEPARTURES = "?destiny=&mov=S&origin_ac="
ARRIVALS ="?origin=&mov=L&origin_ac="
HEADER="flightNumber; plane;; departure_date; departure_time; departure_airport; departure_terminal; departure_status; departure_weather;departure_counter; departure_door;; arrivals_date; arrivals_time; arrivals_airport; arrivals_terminal; arrivals_status; arrivals_weather; arrivals_room; arrivals_belt;; timestam"